# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('1', '物理机'), ('2', '虚拟机'), ('3', '容器'), ('4', '网络设备'), ('5', '安全设备'), ('6', '其他')], max_length=30, null=True, verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '使用中'), ('2', '未使用'), ('3', '故障'), ('4', '其它')], max_length=30, null=True, verbose_name='设备状态'),
        ),
    ]
